[package]
name = "loaner"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "loaner"

[dependencies]
dialoguer = "0.10.2"
comfy-table = "6.1.0"
term_size = "0.3.2"
miette = { version = "5.3.0", features = ["fancy"] }
thiserror = "1.0.37"
